book:
    title:            "Documentación de easybook"
    author:           "Javier Eguiluz"
    edition:          "Primera edición"
    language:         es
    publication_date: ~
    
    generator: { name: easybook, version: 4.0 }
    
    contents:
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: chapter1.md }
        - { element: chapter, number: 2, content: chapter2.md }
        - { element: chapter, number: 3, content: chapter3.md }

    editions:
        print:
            format:         pdf
            include_styles: true
            isbn:           ~
            labels:         ['appendix', 'chapter', 'figure']
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            toc:
                deep:       2
                elements:   ['appendix', 'chapter']
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ['appendix', 'chapter', 'figure']
            toc:
                deep:       2
                elements:   ['appendix', 'chapter']

        website:
            extends:        web
            format:         html_chunked
