book:
    title:            "{{ title }}"
    author:           "Change this: Author Name"
    edition:          "First edition"
    language:         en
    publication_date: ~

    generator: { name: {{ generator.name }}, version: {{ generator.version }} }

    contents:
        # available element types: acknowledgement, appendix, author, chapter,
        # cover, dedication, edition, license, part, title, toc
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: chapter1.md }
        - { element: chapter, number: 2, content: chapter2.md }

    editions:
        print:
            format:         pdf
            include_styles: true
            isbn:           ~
            labels:         ['appendix', 'chapter']  # labels also available for: 'figure', 'table'
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: 'figure', 'table'
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
